apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-scalability
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/edge-experiments/argocd-scalability.git
      revision: main
      directories:
      - path: git-generator-directory/*
  template:
    metadata:
      name: 'argocd-scalability-{{path.basename}}'
      labels:
        generator: git
    spec:
      project: default
      source:
        repoURL: https://github.com/edge-experiments/argocd-scalability.git
        path: '{{path}}/deploy/'
        plugin:
          name: wrap4kyst
      destination:
        server: https://<destination-server-address>:6443
        namespace: argocd-scalability
